# Generated by Django 3.2.9 on 2021-11-26 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Message',
        ),
    ]
